name: Github Pages Deploy
on:
  push:
    branches: [ main ]

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: compile jekyll to gh-pages
        uses: helaili/jekyll-action@v2
        with:
          target_branch: "gh-pages"
          token: ${{ secrets.JEKYLL_PAT }}

